---
# tasks file for mysql
- name: Install MariaDB
  yum: ['mariadb-server.x86_64', 'mariadb-libs.x86_64']
  state: present

- name: Upload Yum Repo Config for MariaDB
  copy:
    src: MariaDB.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root

- name: Upload script for securing mysql
  copy:
    src: mysql-secure-installation.sh
    dest: /var/tmp
    owner: root
    password: root

- name: Run script for securing mysql 
  shell: /var/tmp/mysql-secure-installation.sh >> /var/log/mysql-secure-installation.log





