---
# tasks file for mysql
- name: Upload Yum Repo Config for MariaDB
  copy:
    src: MariaDB.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root

- name: Install MariaDB
  yum: ['mariadb-server.x86_64', 'mariadb-libs.x86_64']
  state: present

- name: Start Maria DB
  systemd:
    name: mariadb
    state: started

- name: Run mysql secure installation script
  shell:  |
    set timeout 5
    spawn mysql_secure_installation

    expect \"Enter current password for root (enter for none):\"
    send \"\r\"

    expect \"Set root password?\"
    send \"Y\r\"

    expect \"New password:\"
    send \"$MYSQL_ROOT_PASSWORD\r\"

    expect \"Re-enter new password:\"
    send \"$MYSQL_ROOT_PASSWORD\r\"

    expect \"Remove anonymous users?\"
    send \"Y\r\"

    expect \"Disallow root login remotely?\"
    send \"Y\r\"

    expect \"Remove test database and access to it?\"
    send \"Y\r\"

    expect \"Reload privilege tables now?\"
    send \"Y\r\"

    expect eof 
  args:
    executable: /usr/bin/expect

- name: Uninstall Expect
  yum: 
    name: expect
    state: absent






