---
# tasks file for php
- name: Install packages for PHP 7 
  yum:
    name: ['php.x86_64', 'php-gd.x86_64', 'php-mbstring.x86_64', 'php-mysqlnd.x86_64', 'php-pdo.x86_64', 'php-pecl-memcache.x86_64']
    state: present
  notify: restart Apache
- name: Upload Webpage 
  copy: 
    src: index.php
    dest: /var/www/html
    owner: root
    group: root